root: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json

env:
  node: true
  mocha: true

plugins:
  - "@typescript-eslint"

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:react/recommended"

rules:
  semi: "warn"
  "@typescript-eslint/no-unused-vars": "off"
  "@typescript-eslint/unbound-method":
    - "error"
    - ignoreStatic: true
  "@typescript-eslint/interface-name-prefix": "off"
  "@typescript-eslint/no-use-before-define": "off"
  "@typescript-eslint/explicit-module-boundary-types": "off"
  no-console: "off"